[[main]]
  name = 'Moebius'
  pageRef = '/'
  weight = 10
[[main]]
  name = 'MÃ¶bius SOL'
  pageRef = '/moebius-sol'
  weight = 40

[[main]]
  name = 'External Links'
  pageRef = '/links'
  weight = 50
