[[main]]
  name = 'Moebius'
  pageRef = '/'
  weight = 10

[[main]]
  name = 'Moebius SOL'
  pageRef = '/moebius-sol'
  weight = 40

[[main]]
  name = 'Externa LÃ¤nkar'
  pageRef = '/links'
  weight = 50
